### PR TITLE
missing Point deserializer 

### LINKED ISSUE #864: DirectionsRoute#fromJson RuntimeException
Originally reported in https://github.com/mapbox/mapbox-navigation-android/issues/1199

> Run into the following 💥 while testing
>
> ```
> 08-08 13:57:37.398 11915-11915/com.mapbox.services.android.navigation.testapp E/NativeMapView: Exception in MapView.OnMapChangedListener
> java.lang.RuntimeException: Failed to invoke public com.mapbox.geojson.Point() with no args
> at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:113)
> at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
> at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
> at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
> at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
> at com.mapbox.api.directions.v5.models.AutoValue_RouteOptions$GsonTypeAdapter.read(AutoValue_RouteOptions.java:339)
> at com.mapbox.api.directions.v5.models.AutoValue_RouteOptions$GsonTypeAdapter.read(AutoValue_RouteOptions.java:35)
> at com.mapbox.api.directions.v5.models.AutoValue_DirectionsRoute$GsonTypeAdapter.read(AutoValue_DirectionsRoute.java:205)
> at com.mapbox.api.directions.v5.models.AutoValue_DirectionsRoute$GsonTypeAdapter.read(AutoValue_DirectionsRoute.java:30)
> at com.google.gson.Gson.fromJson(Gson.java:927)
> at com.google.gson.Gson.fromJson(Gson.java:892)
> at com.google.gson.Gson.fromJson(Gson.java:841)
> at com.google.gson.Gson.fromJson(Gson.java:813)
> at com.mapbox.api.directions.v5.models.DirectionsRoute.fromJson(DirectionsRoute.java:147)
> at com.mapbox.services.android.navigation.ui.v5.NavigationLauncher.extractRoute(NavigationLauncher.java:62)
> at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.extractRoute(MapboxNavigationActivity.java:122)
> at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.onNavigationReady(MapboxNavigationActivity.java:98)
> at com.mapbox.services.android.navigation.ui.v5.NavigationView.onMapReady(NavigationView.java:203)
> at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1157)
> at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:1142)
> at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:900)
> at android.os.MessageQueue.nativePollOnce(Native Method)
> at android.os.MessageQueue.next(MessageQueue.java:323)
> at android.os.Looper.loop(Looper.java:135)
> at android.app.ActivityThread.main(ActivityThread.java:5417)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> Caused by: java.lang.InstantiationException: Can't instantiate abstract class com.mapbox.geojson.Point
> at java.lang.reflect.Constructor.newInstance(Native Method)
> at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:110)
> at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212) 
> at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) 
> at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
> at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
> at com.mapbox.api.directions.v5.models.AutoValue_RouteOptions$GsonTypeAdapter.read(AutoValue_RouteOptions.java:339) 
> at com.mapbox.api.directions.v5.models.AutoValue_RouteOptions$GsonTypeAdapter.read(AutoValue_RouteOptions.java:35) 
> at com.mapbox.api.directions.v5.models.AutoValue_DirectionsRoute$GsonTypeAdapter.read(AutoValue_DirectionsRoute.java:205) 
> at com.mapbox.api.directions.v5.models.AutoValue_DirectionsRoute$GsonTypeAdapter.read(AutoValue_DirectionsRoute.java:30) 
> at com.google.gson.Gson.fromJson(Gson.java:927) 
> at com.google.gson.Gson.fromJson(Gson.java:892) 
> at com.google.gson.Gson.fromJson(Gson.java:841) 
> at com.google.gson.Gson.fromJson(Gson.java:813) 
> at com.mapbox.api.directions.v5.models.DirectionsRoute.fromJson(DirectionsRoute.java:147) 
> at com.mapbox.services.android.navigation.ui.v5.NavigationLauncher.extractRoute(NavigationLauncher.java:62) 
> at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.extractRoute(MapboxNavigationActivity.java:122) 
> at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.onNavigationReady(MapboxNavigationActivity.java:98) 
> at com.mapbox.services.android.navigation.ui.v5.NavigationView.onMapReady(NavigationView.java:203) 
> at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1157) 
> at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:1142) 
> at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:900) 
> at android.os.MessageQueue.nativePollOnce(Native Method) 
> at android.os.MessageQueue.next(MessageQueue.java:323) 
> at android.os.Looper.loop(Looper.java:135) 
> at android.app.ActivityThread.main(ActivityThread.java:5417) 
> at java.lang.reflect.Method.invoke(Native Method) 
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
> ```
>
> Pretty easy to reproduce launching a navigation session using the `NavigationLauncher` 👉 [`NavigationLauncherActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java)
>
> I think introduced by the latest changes in MAS `3.4.0` https://github.com/mapbox/mapbox-navigation-android/pull/1196

> > It looks like the old `DirectionsRoute#fromJson` had some extra adapters / deserializers that were removed https://github.com/mapbox/mapbox-java/pull/854/files#diff-a19faf46d28dec2e35e529c01f8408bdL49
>
> Yeah that seems the issue.

cc @danesfeder

### PR DESCRIPTION
**Pull request by osana**
RouteOptions List<Point> should be serialized as double[][]
closes #864

### CODE REVIEW

File: services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java [hunk 1]
```diff
@@ -190,4 +190,28 @@ public void directionsRequestResult_doesContainOverview() throws Exception {
 
     assertEquals(DirectionsCriteria.OVERVIEW_SIMPLIFIED, route.routeOptions().overview());
   }
+
+  @Test
+  public void toJson_fromJson() throws Exception {
```
Comment (Guardiola31337) [inline services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java]: Normally is good to structure the tests following the triple A 👀 https://speakerdeck.com/guardiola31337/elegant-unit-testing-mobilization-2016?slide=40 http://wiki.c2.com/?ArrangeActAssert
If the `A`rrange part gets too long we should create factory or builder methods.
What about removing some "unnecessary" new lines so that the 3 parts of the test (`A`rrange, `A`ct and `A`ssert) are visually 👌?

File: services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsJsonObject.java [hunk 2]
```diff
@@ -22,6 +24,8 @@
   public String toJson() {
     GsonBuilder gson = new GsonBuilder();
     gson.registerTypeAdapterFactory(DirectionsAdapterFactory.create());
+    // To serialize List<Point> as double [][]
```
Comment (Guardiola31337) [inline services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsJsonObject.java]: NIT - unnecessary comment

File: services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java [hunk 3]
```diff
@@ -126,6 +128,8 @@ public static Builder builder() {
   public static DirectionsResponse fromJson(String json) {
     GsonBuilder gson = new GsonBuilder();
     gson.registerTypeAdapterFactory(DirectionsAdapterFactory.create());
+    // To deserialize RouteOptions:List<Point> from double [][]
```
Comment (Guardiola31337) [inline services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsResponse.java]: NIT - unnecessary comment

File: services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java [hunk 4]
```diff
@@ -144,6 +146,8 @@ public static Builder builder() {
   public static DirectionsRoute fromJson(String json) {
     GsonBuilder gson = new GsonBuilder();
     gson.registerTypeAdapterFactory(DirectionsAdapterFactory.create());
+    // To deserialize RouteOptions: List<Point> from double [][]
```
Comment (Guardiola31337) [inline services-directions/src/main/java/com/mapbox/api/directions/v5/models/DirectionsRoute.java]: NIT - unnecessary comment

File: services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java [hunk 5]
```diff
@@ -289,10 +290,12 @@ public static Builder builder() {
    *   method
    * @since 3.4.0
    */
-  public static RouteLeg fromJson(String json) {
+  public static RouteOptions fromJson(String json) {
     GsonBuilder gson = new GsonBuilder();
     gson.registerTypeAdapterFactory(DirectionsAdapterFactory.create());
-    return gson.create().fromJson(json, RouteLeg.class);
+    // To deserialize List<Point> from double [][]
```
Comment (Guardiola31337) [inline services-directions/src/main/java/com/mapbox/api/directions/v5/models/RouteOptions.java]: NIT - unnecessary comment

File: services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java (hunk 1 above)
Comment (Guardiola31337) [reply services-directions/src/test/java/com/mapbox/api/directions/v5/models/RouteOptionsTest.java]: What about updating the naming here to be more specific / descriptive? The test names should reflect what we're testing so if you 👀 at it you know what's going on at a glance.
